# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Matija Zigic
title: Senior Robotics Engineer
email: zigic.matija@gmail.com 
phone: +385 98 551721
website: matijazigic.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: jekyllrb
github_username:  matijazigic
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: matija-zigic
#xing_username: jekyll
#pinterest_username: jekyll
youtube_username: playlist?list=PL_LbPbX84tKfhAtoTM_5zttlptMTTz1ky
#googleplus_username: +jekyll

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

google_analytics: UA-168928275-1
gtag: UA-168928275-1

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/mz_casual.jpg
about_content: | # this will include new lines to allow paragraphs
  Matija Zigic went to the Faculty of Electrical Engineering and Computing, **University of Zagreb**. 
  He received his Master's degree in 2012. His primary focus was robotics and robust voice activity detection for applications in mobile robotics. 

  After completing his Master's thesis he started working in **Intis** where he worked on different industrial automation tasks worldwide. He was writing software for a company that offers state-of-the-art plant solutions for the metal industry.

  In 2014, he started working for Croatian based startup **Farmeron**. There, he developed cloud-based farm business management software. More precisely, worked on developing mobile applications, backend development, and integration with various hardware devices. 

  In 2017, he accepted the offer from **Aeolus robotics** and started working on bringing the first generation of household robot assistants into people's homes. Worked on an interface between a robot's brain and low-level controllers and simulations. 
  
  In **Gideon Brothers**, as head of the navigation group, he is working on path planning and motio control problems for robots in logistic environments, using all kind of kinematical models. Working on challenging detection and tracking of moving objects problem in
  crowded environments using sensors like 2D/3D sensors. He proudly participated in implementation of multirobot coordiantion algorithm to avoid congestions and deadlocks. 
  More recently, he is working on visual-intertial odometry challenges using sequential images and inertial measurements.


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left #top-middle
        #border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title:  Trailer (un)loading autonomous forklift
        link: https://youtu.be/EcnskOHdL_k
        link_text: Video
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Autonomous forklift that moves pallets from staging lanes and places them directly into the trailer and viceversa.
        #description: | # this will include new lines to allow paragraphs
        #  Description about the work on/with the project
      - layout: left #top-middle
        #border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Industrial omnidirectional heavy load carrying robot
        #link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Omnidirectionat robot that moves large paper rolls from point A to point B.
        #description: | # this will include new lines to allow paragraphs
        #  Description about the work on/with the project
      - layout: left
        #border: weak
        title:  Industrial self-driving forklift
        link: https://youtu.be/QHXtqM1hxqA
        link_text: Video
        #github: 
        quote: >
          Autonomous outrigger type forklift.
        #description: | # this will include new lines to allow paragraphs
      - layout: left
        #border: weak
        title:  GideonBot
        link: https://www.youtube.com/watch?v=dPC0Tclm1Rs
        link_text: Video
        #github: 
        quote: >
          GideonBot solves industrial problems with autonomous mobile robots powered by AI.
        #description: | # this will include new lines to allow paragraphs
      - layout: left
        title:  Household robot assistant
        link: https://www.youtube.com/watch?v=H4-wtJz4IEg
        link_text: Video
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: https://github.com/aeolusbot
        quote: >
          From delivering food to picking up clutter and locating lost items, our robots are always ready to help.
      - layout: left
        title: Continuous casting of long strands of metal
        link: https://www.youtube.com/watch?v=3nW9LyWV72g
        link_text: Video
        quote: >
          Continuous casting is the process where a metal is heated until it liquefies.
        #description: | # this will include new lines to allow paragraphs
        #  Software for the control of manufacturing processes        
  - title: Experience
    layout: list
    # content:
    #   - layout: right
    #     title: Company name
    #     sub_title: Job title
    #     caption: Date Range (eg. November 2016 - present)
    #     link: Link to company (optional)
    #     quote: >
    #       Short description of the company (optional)
    #     description: | # this will include new lines to allow paragraphs
    #       Description of role
    content:
      - layout: right
        title: Gideon Brothers
        link: gideonbros.ai
        sub_title: Senior Robotics Engineer
        caption: March 2017 - Present
        description: | # this will include new lines to allow paragraphs
          * Team lead
          * Path planning algorithms
          * Motio control algorithms
          * Coordination of swarm of robots 
          * Visual-inertial odometry
        quote: >
          Providing global market leaders with automate-to-grow robotic solutions.
      - layout: right
        title: Aeolus Robotics
        link: aeolusbot.com
        sub_title: Robotics Engineer
        caption: June 2017 - March 2018
        quote: >
          Aeolus Robotics is worldwide company bringing the first generation of household robot assistants into people’s home.
        description: | # this will include new lines to allow paragraphs
          * Interface between robot’s brain and low-level microcontrollers
          * Interface to control, test and simulate sensors, arm and base motion
          * Face mimics
      - layout: right
        title: Farmeron
        link: crunchbase.com/organization/farmeron
        sub_title: Software Engineer
        caption: August 2014 - March 2017
        quote: >
          Farmeron helps farmers across the world to manage their farming data online and to do farm performance analysis using exciting statistics. 
        description: | # this will include new lines to allow paragraphs
          * Cloud-based farm business management software
          * Mobile applications and backend development
          * Integration with hardware devices 
      - layout: right
        title: Intis
        link: intis.eu
        sub_title: Automation Engineer
        caption: January 2013 - August 2014
        quote: >
          Engineering and automation of most demanding technological processes.
        description: | # this will include new lines to allow paragraphs
          * Hardware and software design for various branches of industry
          * PLC and SCADA development, Matlab simulations
          * Commissioning worldwide
  - title: Education
    layout: list
    content:
    - layout: left
      title: University of Zagreb
      dates: 2010 - 2012
      sub_title: M.Sc. in Control Engineering and Automation
      quote: >
        Thesis: 'Robust voice activity detection for applications in mobile robotics'
      description: | # this will include new lines to allow paragraphs
        Robotics
    - layout: left
      title: University of Zagreb
      dates: 2007 - 2010
      sub_title: B.Sc. in Control Engineering and Automation
      quote: >
        Thesis: 'Design of electric vehicle voltage converter'
      description: | # this will include new lines to allow paragraphs
        Control Engineering
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      <mark> Robotics and AI </mark> : Robotics, ROS, Machine Learning, AI

      <mark> Sensors </mark>: LIDAR, Stereo, RGB-D, Sonar

      <mark> Languages </mark> : C, C++, Python, Java

      <mark> DevOps </mark> : Linux, Scripting, Docker, SQL

      <mark> Automation </mark> : PLC, SCADA

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed
  

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
